tailwindConfig: "./tailwind.config.js"
trailingComma: "es5"
arrowParens: "avoid"
printWidth: 81
tabWidth: 3
useTabs: false
semi: true
quoteProps: "as-needed"
jsxSingleQuote: false
singleQuote: false
bracketSpacing: true
bracketSameLine: false
proseWrap: "always"
endOfLine: "lf"
